# Generated by Django 4.2.7 on 2023-11-19 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="mycalcvalue",
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name="person",
            name="userinputvalue",
            field=models.CharField(max_length=300),
        ),
    ]
