# Generated by Django 4.2.7 on 2023-11-19 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_alter_person_mycalcvalue_alter_person_userinputvalue"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="mycalcvalue",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="person",
            name="userinputvalue",
            field=models.CharField(max_length=30),
        ),
    ]
